import { ANIME, MANGA } from './providers';
import { PROVIDERS_LIST } from './utils/providers-list';
import {
  GogoCDN,
  RapidCloud,
  StreamSB,
  StreamTape,
  VidCloud,
} from './extractors';
import {
  IProviderStats,
  ISearch,
  IAnimeEpisode,
  IAnimeInfo,
  IAnimeResult,
  IEpisodeServer,
  IVideo,
  StreamingServers,
  MediaStatus,
  SubOrSub,
  IMangaResult,
  IMangaChapter,
  IMangaInfo,
  IMangaChapterPage,
  ISource,
  ISubtitle,
  Intro,
  Genres,
  FuzzyDate,
  ITitle,
  MediaFormat,
  ProxyConfig,
} from './models';

export { ANIME, MANGA };
export { PROVIDERS_LIST };
export {
  Genres,
  SubOrSub,
  StreamingServers,
  MediaStatus,
  IProviderStats,
  IAnimeEpisode,
  IAnimeInfo,
  IAnimeResult,
  IEpisodeServer,
  IVideo,
  IMangaResult,
  IMangaChapter,
  IMangaInfo,
  ISearch,
  IMangaChapterPage,
  ISource,
  ISubtitle,
  Intro,
  FuzzyDate,
  ITitle,
  MediaFormat,
  ProxyConfig,
  GogoCDN,
  StreamSB,
  VidCloud,
  RapidCloud,
  StreamTape,
};
